version: '3'

services:
  speech-to-text-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - ./sttkey.json:/app/sttkey.json:ro
    environment:
      - NODE_ENV=production
      - PORT=8081 